apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "swapi-spring-webflux"
    version: "0.0.3-SNAPSHOT"
    group: "swapi"
  name: "swapi-spring-webflux"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "swapi-spring-webflux"
      version: "0.0.3-SNAPSHOT"
      group: "swapi"
  template:
    metadata:
      labels:
        app: "swapi-spring-webflux"
        version: "0.0.3-SNAPSHOT"
        group: "swapi"
    spec:
      containers:
        - name: "swapi-spring-webflux"
          image: "docker.local/swapi/swapi-spring-webflux:0.0.3-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              path: "/actuator/info"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              name: "http"
              protocol: "TCP"
          env:
            - name: "spring.profiles.active"
              value: postgresql
            - name: "spring.datasource.url"
              value: "jdbc:postgresql://swapi-db:5432/swapi"
            - name: "spring.datasource.username"
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: POSTGRES_USER
            - name: "spring.datasource.password"
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
      imagePullSecrets:
        - name: docker-local-registry-creds
