apiVersion: v1
kind: ConfigMap
metadata:
  name: swapi-filebeat-config
  labels:
    k8s-app: filebeat
    group: swapi
data:
  filebeat.yml: |-
    filebeat:
      inputs:
        - type: log
          enabled: true
          #max_bytes: 10485760
          json:
            keys_under_root: true
            add_error_key: true
            message_key: message
          paths:
            - /var/log/*.json

    fields:
      app.name: swapi-spring-web
      app.version: 0.0.4-SNAPSHOT
      logsource.stage: dev

    output:
      elasticsearch:
        enabled: true
        hosts: ["elasticsearch-master.elk:9200"]
        index: "springapp-%{+yyyy.MM.dd}"

    setup.template:
      enabled: true
      name: "springapp"
      pattern: "springapp-*"

    setup.ilm.enabled: false
---